package com.crazine.goo2tool.gamefiles.fistyini;

import java.util.List;

public class DefaultFistyIni {
    
    public static final String[] BALL_TABLE = new String[] {
        "Invalid",
        "Common",
        "CommonAlbino",
        "Ivy",
        "Balloon",
        "GoolfSingle",
        "Anchor",
        "LauncherL2B",
        "GooProduct",
        "Thruster",
        "Terrain",
        "BalloonEye",
        "Conduit",
        "LauncherL2L",
        "GooProductWhite",
        "Grow",
        "BombSticky",
        "Rope",
        "Bouncy",
        "Fish",
        "TimeBug",
        "",
        "",
        "MatchStick",
        "CommonWorld",
        "Fireworks",
        "Lightball",
        "TwuBit",
        "TwuBitBit",
        "Adapter",
        "Winch",
        "",
        "Shrink",
        "Jelly",
        "Goolf",
        "ThisWayUp",
        "LiquidLevelExit",
        "Eye",
        "UtilAttachWalkable",
    };

    // TODO: Update version number
    private static final String BALL_TABLE_HEADER = """
            ; This table defines all Gooball typeEnums
            ; Extend this list to add your own gooballs.
            ;\s
            ; Generated by Goo2Tool 1.0
            
            """;

    public static FistyIniFile generateBallTable() {
        StringBuilder builder = new StringBuilder(BALL_TABLE_HEADER);
        
        for (int i = 0; i < BALL_TABLE.length; i++) {
            builder.append(i).append('=').append(BALL_TABLE[i]).append('\n');
        }
        
        return new FistyIniFile(builder.toString(), List.of(BALL_TABLE));
    }
    
}
